### ISSUE TITLE
Configurable HWM

### ISSUE THREAD

**Issue by tj** [segmentio/analytics-go#14]

**Comment by achille-roussel** [comment]
@f2prateek have we build this in one of the other libraries?

**Comment by f2prateek** [comment]
I wasn't sure what this really meant /shrug

**Comment by achille-roussel** [comment]
Calvin said it was meant to define a *high watermark* for how many messages are sent... not really sure what the use case was for this.

If you don't mind I think we can close the issue.

**Comment by f2prateek** [comment]
yeah @calvinfo can chime in here - fine with me either way.

**Comment by calvinfo** [comment]
I think the general use case would be if you don't want tracking calls to block when the channel fills up, so you can configure a larger size. That said, I don't think we've had many folks ask for it, so I'm okay omitting it until they do

**Comment by f2prateek** [comment]
We do already support this right? We have a default batch size, but people can set their own.

**Comment by calvinfo** [comment]
I suppose if you create your own msgs channel, then you can yes

**Comment by achille-roussel** [comment]
With the current implementation the tracking calls would block if the channel fills but this blocking operation would be really short since the goroutine that flushes the channel doesn't block on the HTTP requests anymore (we've made it asynchronous). So blocking here would mean there are already 100 messages in the input channel, it's kind of sane in my opinion to block in this case because the application is producing way faster than the consumer can process.

This looks like it could be a common case because there are usually many producer threads for a single consumer thread, but in practice the application is spending way more time doing its own work compared to pushing messages to the client, and the consumer is only pulling messages from the channel so I believe the `Enqueue` call would never block in practice.

What we can do right now is log an error message if the call ever blocks so the application gets a trace that it happened and if someone notices the issue we can figure out with them their use case and how to fix it. For example:
```go
select {
case c.msgs <- msg:
default:
    t0 := time.Now()
    c.msgs <- msg
    t1 := time.Now()
    c.errorf("the message channel was full - blocked for %s", t1 - t0)
}
```

**Comment by achille-roussel** [comment]
I'll close this as the feature hasn't been requested, we now have failure callbacks implemented we a hard limit on the number of internal in-flight messages which kind of covers this topic.

Feel free to re-open if you think there's a need for this feature.
