### ISSUE TITLE
Length of messages channel will never exceed Size, and so will never flush

### ISSUE THREAD

**Issue by amzuko** [segmentio/analytics-go#39]
So in analytics.go line 298 we have:

if len(msgs) == c.Size {
...flush...
}

However, msgs is initialized with capacity 100, and Size is initialized with length 250 -- should these two numbers be swapped?

**Comment by yields** [comment]
What version are you using?

**Comment by f2prateek** [comment]
@amzuko I think there is confusion because of the naming of the variable. 

Although the `msgs` channel is [initialized](https://github.com/segmentio/analytics-go/blob/master/analytics.go#L140) with a bound of 100, the line you are [referring to](https://github.com/segmentio/analytics-go/blob/master/analytics.go#L321) is comparing this [local `msgs` array](https://github.com/segmentio/analytics-go/blob/master/analytics.go#L313) and not the global `msgs` channel. This local array can easily grow over 250 in size since it's unbounded.
