### ISSUE TITLE
Make analytics.Client an interface

### ISSUE THREAD

**Issue by achille-roussel** [segmentio/analytics-go#51]
@f2prateek 

What do you think about making the `analytics.Client` an interface, from the current PRs it looks like we're moving toward having all fields being unexported, which means there's no much need for the actual type to be exposed.

The interface can look like this:
```go
type Client interface {
    io.Closer

    Alias(*Alias) error

    Page(*Page) error

    Group(*Group) error

    Identify(*Identify) error

    Track(*Track) error
}
```
This way we could also have a `type MockClient struct{}` which implements this interface and can be used in test code for example.

Let me know what you think about it.

**Comment by f2prateek** [comment]
Yeah exposing an interface instead of a concrete type is certainly a good idea.

Unsure if it's necessary for us, since I do think that for testing most people have preferred to point our sdks to a mock server instead of simply mocking the interface. But giving people the option to do both wouldn't hurt.
