### ISSUE TITLE
Change Integrations to a map[string]bool

### ISSUE THREAD

**Issue by achille-roussel** [segmentio/analytics-go#60]
@f2prateek 
@calvinfo 

From what I read in the documentations, integration objects are of the form `{ all: true, something: false }`, so the values are always booleans.

How about changing the `Integrations` fields type to `map[string]bool` so we can leverage the compiler to check that the program is doing it right.

**Comment by f2prateek** [comment]
Ah we'd want to leave it as a `map[string]interface{}`. The reason is that this is a way for users to pass certain options specific to integrations. We don't advertise it too much though.

e.g. `analytics.track('hello', { integrations: { Mailchimp: { listId: 123456 } } })`

https://github.com/segment-integrations/integration-mailchimp/blob/8c23e8df3ed91c14d0a06a01a35e0c9b564e14cf/test/fixtures/identify-override-list-id.json#L14-L18

If any value (not `false`) is provided for the integration, we consider it enabled.

**Comment by achille-roussel** [comment]
OK, thanks for your insights on that 👍

**Comment by f2prateek** [comment]
FWIW to make it safer for clients in Java, the underlying type is [`map[string]interface{}`](https://github.com/segmentio/analytics-java/blob/master/analytics-core/src/main/java/com/segment/analytics/messages/Message.java#L35) but it's insulated by the builder API - `https://github.com/segmentio/analytics-java/blob/master/analytics-core/src/main/java/com/segment/analytics/messages/MessageBuilder.java#L91-L123`.

This way clients can not pass `{ integrations: { Mailchimp:  123456 } }` - they must pass either a boolean, or a map under Mailchimp.

**Comment by achille-roussel** [comment]
I see, thanks for the details.

I think I'm comfortable with the current level of flexibility we have, if the values are heterogenous types it should be `interface{}` no need to increase the complexity for little safety gains (at some point developers need to read the doc 📖 ).
