### ISSUE TITLE
len(msgs) >= c.Size

### ISSUE THREAD

**Issue by paddie** [segmentio/analytics-go#68]
This would prevent the buffer never being emptied if someone sets to size to 0:

```go
// https://github.com/segmentio/analytics-go/blob/master/analytics.go#L316
for {
		select {
		case msg := <-c.msgs:
			c.verbose("buffer (%d/%d) %v", len(msgs), c.Size, msg)
			msgs = append(msgs, msg)
			if len(msgs) == c.Size {
				c.verbose("exceeded %d messages – flushing", c.Size)
				c.send(msgs)
				msgs = nil
```

**Comment by achille-roussel** [comment]
A batch size of zero is actually an invalid value in this version, since it's not actually a bug I'd rather not change the logic and just let it work the way it is now.

A batch size of zero will be understood as *"use the default batch size"* in future releases.

I'll close this issue but please feel free to reopen if you see this to be a problem in some cases.
