### ISSUE TITLE
Client blocks for the duration of the batch marshal and post (including retries)

### ISSUE THREAD

**Issue by paddie** [segmentio/analytics-go#72]
When the loop receives a message and `len(msgs) == c.size` the list of messages are marshalled into json and sent. When doing this, the client will accept messages up until the buffer channel buffer size, and the block. Worst case, this will be: 
```
jsonMarshalTime + 10 * http-roundtrip + ExponentialRetries
```

This could be a potentially long time (in CPU terms), all the while the client would be unresponsive or just blocking other calls to client.Track etc.

Since whatever errors or complications happened during the send does not really result in anything but a call to log, it might make sense to do this completely async/concurrently.

**Comment by achille-roussel** [comment]
Yes we've recently had discussions about this, we're probably gonna go with just spawning a goroutine to post the message chunks so it doesn't block.

There needs to be some sort of synchronization involved via a `sync.WaitGroup` or similar tho because when a client is closed we block the goroutine calling `Close` until all messages have been flushed so the code needs to wait for all those async uploads to complete.

**Comment by paddie** [comment]
Aye, the pull-request referencing this issue addresses that as well.
